[package]
name = "rustbrush"
version = "0.2.0"
edition = "2021"
description = "An automatic sign painter for Rust (the game)"
license = "MIT"

[[bin]]
name = "rustbrush"
path = "src/main.rs"

[[bin]]
name = "rustbrush-gui"
path = "src/gui.rs"

[dependencies]
rustbrush-core = { path = "../rustbrush-core" }
rustbrush-platform = { path = "../rustbrush-platform" }
clap = { version = "4", features = ["derive"] }
image = "0.25"
device_query = "2"
log = "0.4"
env_logger = "0.11"
eframe = "0.33"
egui_extras = { version = "0.33", features = ["image"] }
rfd = "0.17"
portable-atomic = "1.13.1"
font-kit = "0.14"
